# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core', '~> 5.20.1'
target 'AppLearn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppLearn

  target 'AppLearn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


