# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppLearn' do
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

end


